version: '3.8'

services:
  ollama:
    image: voasd00/ielts-ollama-custom:latest
    platform: linux/amd64
    container_name: ollama-service
    ports:
      - "8080:8080"
    volumes:
      - ./ollama/ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    image: voasd00/ielts-fastapi-backend:latest
    platform: linux/amd64
    container_name: fastapi-backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    volumes:
      - ./backend:/app
    restart: unless-stopped