# 1. Base image with platform specification and Python 3.11.9
FROM --platform=linux/amd64 python:3.11.9-slim

# 2. Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TF_CPP_MIN_LOG_LEVEL=2

# 3. Install system dependencies
RUN apt-get update && \
    apt-get install -y curl ca-certificates gnupg git wget git-lfs dos2unix build-essential && \
    git lfs install && \
    rm -rf /var/lib/apt/lists/*

# 5. Set working directory
WORKDIR /app

# 6. Copy your code into the container
COPY requirements.txt .

RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

# 10. Start Ollama and your FastAPI app
CMD ["python", "main.py"]