# 1. Base image with platform specification and Python 3.12
FROM --platform=linux/amd64 python:3.12-slim

# 2. Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Install system dependencies
RUN apt-get update && \
    apt-get install -y curl ca-certificates gnupg git wget git-lfs dos2unix build-essential && \
    git lfs install && \
    rm -rf /var/lib/apt/lists/*

# 5. Set working directory
WORKDIR /app

# 6. Copy your code into the container
COPY requirements.txt .

RUN pip install pip==25.1 setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

# 10. Start Ollama and your FastAPI app
CMD ["python", "main.py"]