apiVersion: apps/v1
kind: Deployment
metadata:
  name: ielts-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ielts-backend
  template:
    metadata:
      labels:
        app: ielts-backend
    spec:
      containers:
        - name: ielts-backend
          image: backend_image
          imagePullPolicy: Always  
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: secrets
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "6Gi"
              cpu: "2000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ielts-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ielts-frontend
  template:
    metadata:
      labels:
        app: ielts-frontend
    spec:
      containers:
        - name: ielts-frontend
          image: frontend_image
          imagePullPolicy: Always  
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: secrets

