apiVersion: v1
kind: Service
metadata:
  name: ielts-backend
spec:
  selector:
    app: ielts-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  # This exposes the service externally with an external IP address
