name: BACKEND DOCKERIZATION

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - '.github/workflows/backend-dockerization.yml'
jobs:
  setup-build-publish-deploy:
    env:
      PROJECT_ID: '${{ secrets.PROJECT_ID }}'
      GAR_LOCATION: 'asia-southeast2'
      GKE_CLUSTER: 'ielts-cluster' 
      GKE_ZONE: 'asia-southeast2'  
      DEPLOYMENT_NAME_1: 'ielts-backend'  
      REPOSITORY: 'ielts-repo'  
      WORKLOAD_IDENTITY_PROVIDER: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'

    name: 'BACKEND Setup, Build and Publish'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-wif@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Setup gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'  # Ensure this outputs the correct token
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          
      - name: 'Build and push Docker containers'
        run: |-
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain
          BACKEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/ielts-backend:latest"
          # Set your build arguments
          echo "Building frontend container: $BACKEND_TAG"
          docker build -f backend/Dockerfile.backend --tag "${BACKEND_TAG}" backend/
          docker push "${BACKEND_TAG}"
      - name: 'Deploy to Cloud Run'
        run: |-
          BACKEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/ielts-backend:latest"
          echo "🚀 Deploying backend image to Cloud Run..."
          gcloud run deploy ielts-backend \
            --project="${PROJECT_ID}" \
            --image="${BACKEND_TAG}" \
            --region="asia-southeast1" \
            --platform=managed \
            --memory=16Gi \
            --cpu=4 \
            --timeout=300 \
            --concurrency=80 \
            --max-instances=1 \
            --service-account=151828473868-compute@developer.gserviceaccount.com \
            --port=8080 \
            --set-env-vars="BAND_DISCRIPTIOR_FILE=${{ secrets.BAND_DISCRIPTIOR_FILE }},GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_API_KEY_2=${{ secrets.GEMINI_API_KEY_2 }},GEMINI_API_KEY_3=${{ secrets.GEMINI_API_KEY_3 }},IELTS_HUGGINGFACE_API_KEY=${{ secrets.IELTS_HUGGINGFACE_API_KEY }},MAX_RETRIES=${{ secrets.MAX_RETRIES }},MONGODB_DB_NAME=${{ secrets.MONGODB_DB_NAME }},MONGODB_URI=${{ secrets.MONGODB_URI }},OLLAMA_URL=${{ secrets.OLLAMA_URL }},RETRY_DELAY=2" \
            --cpu-boost \
            --allow-unauthenticated \
            --args=""

          
