name: FRONTEND DOCKERIZATION

on:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-dockerization.yml'

jobs:
  setup-build-publish-deploy:
    env:
      PROJECT_ID: '${{ secrets.PROJECT_ID }}'
      GAR_LOCATION: 'asia-southeast2'
      GKE_CLUSTER: 'ielts-cluster'
      GKE_ZONE: 'asia-southeast2'
      DEPLOYMENT_NAME_1: 'ielts-frontend'
      REPOSITORY: 'ielts-repo'
      WORKLOAD_IDENTITY_PROVIDER: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'

    name: 'FRONTEND Setup, Build and Publish'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-wif@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Setup gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Create env file for frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}" >> .env.local
        working-directory: ./frontend

      - name: 'Build and push Docker containers'
        run: |-
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain
          FRONTEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/ielts-frontend:latest"
          echo "Building frontend container: $FRONTEND_TAG"
          docker build -f frontend/Dockerfile.frontend --tag "${FRONTEND_TAG}" frontend/
          docker push "${FRONTEND_TAG}"

      - name: 'Deploy frontend to Cloud Run'
        run: |-
          FRONTEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/ielts-frontend:latest"

          echo "🚀 Deploying frontend image to Cloud Run..."
          gcloud run deploy ielts-frontend \
            --project="${PROJECT_ID}" \
            --image="${FRONTEND_TAG}" \
            --region="asia-southeast1" \
            --platform=managed \
            --memory=512Mi \
            --cpu=1 \
            --timeout=60 \
            --concurrency=80 \
            --max-instances=3 \
            --port=8080 \
            --service-account=151828473868-compute@developer.gserviceaccount.com \
            --set-env-vars="NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" \
            --allow-unauthenticated



