name: FRONTEND DOCKERIZATION

on:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      - 'k8s/base/**'
      - '.github/workflows/gke-frontend.yml'

jobs:
  setup-build-publish-deploy:
    env:
      PROJECT_ID: '${{ secrets.PROJECT_ID }}'
      GAR_LOCATION: 'asia-southeast2'
      GKE_CLUSTER: 'ielts-cluster'
      GKE_ZONE: 'asia-southeast2'
      DEPLOYMENT_NAME_1: 'ielts-frontend'
      REPOSITORY: 'ielts-repo'
      WORKLOAD_IDENTITY_PROVIDER: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'

    name: 'FRONTEND Setup, Build and Publish'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-wif@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Setup gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Build and push Docker containers'
        run: |-
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain
          FRONTEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/ielts-frontend:latest"
          echo "Building frontend container: $FRONTEND_TAG"
          docker build -f frontend/Dockerfile.frontend --tag "${FRONTEND_TAG}" frontend/
          docker push "${FRONTEND_TAG}"



