name: 'BACKEND Build and Deploy to GKE'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - 'k8s/base/**'
      - '.github/workflows/gke-backend.yml'
jobs:
  setup-build-publish-deploy:
    env:
      PROJECT_ID: '${{ secrets.PROJECT_ID }}'  # TODO: update to your Google Cloud project ID
      GAR_LOCATION: 'asia-southeast2'  # TODO: update to your region
      GKE_CLUSTER: 'ielts-cluster'  # TODO: update to your cluster name
      GKE_ZONE: 'asia-southeast2'  # TODO: update to your cluster zone
      DEPLOYMENT_NAME_1: 'ielts-backend'  # TODO: update to your deployment name
      REPOSITORY: 'ielts-repo'  # TODO: update to your Artifact Registry docker repository name
      WORKLOAD_IDENTITY_PROVIDER: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
    name: 'BACKEND Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checkout code
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-wif@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Setup gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'  # Ensure this outputs the correct token
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Set up GKE credentials and Install GKE gcloud auth plugin'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'
          project_id: '${{ env.PROJECT_ID }}'

      - run: |
          set -x  # Enable command tracing for debugging
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
          gcloud components update
          gcloud components install gke-gcloud-auth-plugin
      - name: 'Create Kubernetes Secret/Config'
        run: |
          kubectl create secret generic secrets \
            --from-literal=MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --from-literal=MONGODB_DB_NAME="${{ secrets.MONGODB_DB_NAME }}" \
            --from-literal=IELTS_HUGGINGFACE_API_KEY="${{ secrets.IELTS_HUGGINGFACE_API_KEY }}" \
            --from-literal=OLLAMA_URL="${{ secrets.OLLAMA_URL }}" \
            --from-literal=MAX_RETRIES="${{ secrets.MAX_RETRIES }}" \
            --from-literal=RETRY_DELAY="${{ secrets.RETRY_DELAY }}" \
            --from-literal=GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            --from-literal=GEMINI_API_KEY_2="${{ secrets.GEMINI_API_KEY_2 }}" \
            --from-literal=GEMINI_API_KEY_3="${{ secrets.GEMINI_API_KEY_3 }}" \
            --from-literal=BAND_DISCRIPTIOR_FILE="${{ secrets.BAND_DISCRIPTIOR_FILE }}" \
            --from-literal=NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL }}" \
            --dry-run=client -o yaml | kubectl apply -f -
      - name: 'Build and push Docker containers'
        run: |-
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain
          BACKEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/ielts-backend:latest"
          # Set your build arguments
          echo "Building frontend container: $BACKEND_TAG"
          docker build -f backend/Dockerfile.backend --tag "${BACKEND_TAG}" backend/
          docker push "${BACKEND_TAG}"

      - name: 'Deploy to GKE'
        run: |-
          set -x  # Enable command tracing for debugging
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
          # apply secrets by using kubectl command
          BACKEND_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/ielts-backend:latest"
          sed -i "s|image: backend_image|image: ${BACKEND_TAG}|" k8s/base/deployment.yaml
          kubectl apply -f k8s/base/deployment.yaml
          kubectl apply -f k8s/base/service.yaml
          # Restart the deployment to apply the new image
          kubectl get deployment $DEPLOYMENT_NAME_1 && \
          kubectl rollout restart deployment/$DEPLOYMENT_NAME_1 || \
          echo "Deployment $DEPLOYMENT_NAME_1 not found. Skipping restart."
          

          
